### ISSUE TITLE
Address GWAS scaling issues

### ISSUE THREAD

**Issue by tomwhite** [related-sciences/ukb-gwas-pipeline-nealelab#37]
Documented at https://github.com/pystatgen/sgkit/issues/390 and related issues.

This is an umbrella issue for

- [ ] Upgrade to dask 2.30.1+ #27
- [ ] Rechunk dosages so there is no chunking in the samples dimension #35
- [ ] Run on preemptible instances #36

following recommendations in https://github.com/pystatgen/sgkit/issues/390#issuecomment-781503522
